name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 1.1.0
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.4+1
  http: ^1.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11